provider:
  asn: 65000
  underlay: isis-level-2
  routers:
    PE1:
      role: pe
      platform: frrdocker
      version: "10.3"
      loopback: 10.255.0.1/32
      recovery_profile: pe
    P1:
      role: p
      platform: frrdocker
      version: "10.3"
      loopback: 10.255.0.2/32
      recovery_profile: core
    P2:
      role: p
      platform: frrdocker
      version: "10.3"
      loopback: 10.255.0.3/32
      recovery_profile: core
    PE2:
      role: pe
      platform: frrdocker
      version: "10.3"
      loopback: 10.255.0.4/32
      recovery_profile: pe

customers:
  CUST-A:
    asn: 65100
    route_target: "65000:100"
    sites:
      CE-A1:
        platform: mikrotik_chr
        version: "7.22.1"
        pe_address: 172.16.1.2/30
        lan: 10.10.10.0/24
      CE-A2:
        platform: mikrotik_chr
        version: "7.22.1"
        pe_address: 172.16.2.2/30
        lan: 10.10.20.0/24
  CUST-B:
    asn: 65200
    route_target: "65000:200"
    sites:
      CE-B1:
        platform: mikrotik_chr
        version: "7.22.1"
        pe_address: 172.17.1.2/30
        lan: 10.10.10.0/24
      CE-B2:
        platform: mikrotik_chr
        version: "7.22.1"
        pe_address: 172.17.2.2/30
        lan: 10.10.20.0/24
